"use client"

import { useState } from "react"
import { useApp } from "@/components/app-context"
import { Button, Checkbox } from "@/components/ui-kit"
import { PageContainer, PageHeading } from "@/components/page-parts"
import { IDEATOR_IDEAS, AI_SOURCE_COLORS } from "@/lib/data"
import { ArrowUp, Plus, Minus, Sparkles, FileText, RefreshCw } from "lucide-react"

export default function IdeatorPage() {
  const { toast } = useApp()
  const [query, setQuery] = useState(
    "How does Pwinly solution enable the creation of autogenerated written content, from multiple sources?",
  )
  const [sources, setSources] = useState({
    "Library AI": true,
    "Creative AI": true,
    "Internet AI": true,
  })
  const [ideas, setIdeas] = useState<{ text: string; source: string }[] | null>(null)
  const [custom, setCustom] = useState("")

  const generate = () => {
    setIdeas([...IDEATOR_IDEAS])
    toast("Generated 8 ideas")
  }

  return (
    <PageContainer>
      <PageHeading
        title="Ideator"
        subtitle="Generate idea fragments from your sources, then assemble them into structured paragraphs."
      />

      {ideas && (
        <div className="mt-6 grid grid-cols-1 gap-3 sm:grid-cols-2 lg:grid-cols-3">
          {ideas.map((idea, i) => (
            <div
              key={i}
              className="group flex flex-col rounded-xl border border-border bg-card p-4 transition-fast hover:border-primary/40 hover:shadow-sm"
            >
              <div className="mb-2 flex items-center justify-between">
                <span
                  className="rounded-full px-2 py-0.5 text-[10px] font-medium"
                  style={{
                    backgroundColor: `${AI_SOURCE_COLORS[idea.source]}1a`,
                    color: AI_SOURCE_COLORS[idea.source],
                  }}
                >
                  {idea.source}
                </span>
                <button
                  aria-label="Remove idea"
                  onClick={() => setIdeas((arr) => arr!.filter((_, idx) => idx !== i))}
                  className="flex h-6 w-6 items-center justify-center rounded-md text-muted-foreground opacity-0 transition-fast hover:bg-muted group-hover:opacity-100"
                >
                  <Minus className="h-3.5 w-3.5" />
                </button>
              </div>
              <p className="flex-1 text-[13px] leading-relaxed text-foreground">
                {idea.text}
              </p>
              <button
                onClick={() => toast("Added to document")}
                className="mt-3 inline-flex items-center gap-1.5 self-start rounded-md bg-primary/10 px-2.5 py-1 text-[12px] font-semibold text-primary transition-fast hover:bg-primary/20"
              >
                <Plus className="h-3.5 w-3.5" />
                Add
              </button>
            </div>
          ))}
        </div>
      )}

      <div className="mx-auto mt-8 max-w-3xl">
        <div className="rounded-2xl border border-border bg-card p-4 shadow-sm">
          <textarea
            value={query}
            onChange={(e) => setQuery(e.target.value)}
            rows={2}
            className="w-full resize-none border-none bg-transparent text-[15px] leading-relaxed text-foreground outline-none"
          />
          <div className="mt-3 flex flex-wrap items-center justify-between gap-2 border-t border-border pt-3">
            <div className="flex gap-2">
              <Button
                variant="outline"
                size="sm"
                icon={<Plus className="h-3.5 w-3.5" />}
                onClick={() => toast("Add context")}
              >
                Add Context
              </Button>
              <Button
                variant="outline"
                size="sm"
                icon={<Sparkles className="h-3.5 w-3.5" />}
                onClick={() => toast("Modify ideas")}
              >
                Modify Ideas
              </Button>
            </div>
            <button
              aria-label="Generate ideas"
              onClick={generate}
              className="flex h-9 w-9 items-center justify-center rounded-full bg-foreground text-background transition-fast hover:opacity-90"
            >
              <ArrowUp className="h-4 w-4" />
            </button>
          </div>
        </div>

        <div className="mt-4 flex flex-wrap items-center gap-4">
          <span className="text-[13px] font-medium text-muted-foreground">Use:</span>
          {(Object.keys(sources) as (keyof typeof sources)[]).map((s) => (
            <label key={s} className="flex cursor-pointer items-center gap-2 text-[13px]">
              <Checkbox
                checked={sources[s]}
                onChange={(v) => setSources((p) => ({ ...p, [s]: v }))}
              />
              <span
                className="h-2 w-2 rounded-full"
                style={{ backgroundColor: AI_SOURCE_COLORS[s] }}
              />
              {s}
            </label>
          ))}
        </div>

        <div className="mt-4 flex flex-wrap items-center gap-2">
          <div className="flex flex-1 items-center gap-2 rounded-lg border border-border bg-card px-3">
            <FileText className="h-4 w-4 text-muted-foreground" />
            <input
              value={custom}
              onChange={(e) => setCustom(e.target.value)}
              placeholder="Enter a custom idea"
              className="h-9 flex-1 border-none bg-transparent text-[13px] outline-none"
            />
            <button
              aria-label="Refresh"
              onClick={() => toast("Refreshed")}
              className="text-muted-foreground hover:text-primary"
            >
              <RefreshCw className="h-4 w-4" />
            </button>
          </div>
          <Button icon={<Plus className="h-4 w-4" />} onClick={() => toast("Paragraphs generated")}>
            Generate Paragraphs
          </Button>
        </div>
      </div>
    </PageContainer>
  )
}
